version: '3.7'
# reference from https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
# reference from https://www.elastic.co/guide/en/kibana/current/docker.html

services:
  es01:
    build: ./elasticsearch
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - /var/lib/docker/data/bones/es/usr/local/scripts:/usr/local/scripts
      - /var/lib/docker/data/bones/es/usr/local/imports:/usr/local/imports:rw
    ports:
      - 9200:9200
    networks:
      - elastic

  es02:
    build: ./elasticsearch
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es03,es01
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - /var/lib/docker/data/bones/es/usr/local/scripts:/usr/local/scripts
    ports:
      - 9201:9200
    networks:
      - elastic

  es03:
    build: ./elasticsearch
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
      - /var/lib/docker/data/bones/es/usr/local/scripts:/usr/local/scripts
    ports:
      - 9202:9200
    networks:
      - elastic

  kibana:
    build: ./kibana
    container_name: kibana
    links:
      - es01:elasticsearch
    ports:
      - 5601:5601
    networks:
      - elastic


volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
